### PR TITLE
Remove some triple dict lookups and logic in favor of simpler dict.pop usage

### PR DESCRIPTION
**Pull request by terrycojones**
This is just a code clean up that should (in theory!) have no effect.

I tested via `make test_asyncio`. Should I be doing more testing? I don't have a python2 virtualenv handy, though I could of course make one. Or should I be using `tox`? (I tried running just `tox` and get a permission denied error).

### CODE REVIEW

**Comment by meejah** [comment]
Running 'tox' by itself from the root *should* work (it makes its own venvs in .tox/)

**Comment by meejah** [comment]
As far as this PR, looks good thanks :)

(Testing wise travis-ci runs all the utests which have passed...but dont necessarily cover this code of course ;) )

**Comment by terrycojones** [comment]
Actually, some of those original `dict` lookups are quadruple :-)  (Counting the `del`)

**Comment by terrycojones** [comment]
@meejah - thanks for the help. When I run `tox` I get the following:

```
$ tox
GLOB sdist-make: /Users/terry/s/net/AutobahnPython/setup.py
flake8
pypy-twtrunk
pypy-trollius
py34-twtrunk
pypy-tw121 create: /Users/terry/s/net/AutobahnPython/.tox/flake8
pypy-twtrunk
pypy-trollius
py34-twtrunk
pypy-tw121
flake8
pypy-twtrunk
pypy-trollius
py34-twtrunk
pypy-tw121 installdeps: mock, unittest2, coverage, msgpack-python, Twisted==12.1
ERROR: invocation failed (errno 13), args: [local('/Users/terry/s/net/AutobahnPython/.tox/flake8\npypy-twtrunk\npypy-trollius\npy34-twtrunk\npypy-tw121/bin/pip'), 'install', 'mock', 'unittest2', 'coverage', 'msgpack-python', 'Twisted==12.1'], cwd: /Users/terry/s/net/AutobahnPython
Traceback (most recent call last):
  File "/Users/terry/.virtualenvs/lmwamp/bin/tox", line 9, in <module>
    load_entry_point('tox==1.9.2', 'console_scripts', 'tox')()
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_cmdline.py", line 26, in main
    retcode = Session(config).runcommand()
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_cmdline.py", line 339, in runcommand
    return self.subcommand_test()
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_cmdline.py", line 477, in subcommand_test
    if self.setupenv(venv):
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_cmdline.py", line 396, in setupenv
    status = venv.update(action=action)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_venv.py", line 140, in update
    self.install_deps(action)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_venv.py", line 254, in install_deps
    self._install(deps, action=action)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_venv.py", line 322, in _install
    action=action, extraenv=extraenv)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_venv.py", line 288, in run_install_command
    extraenv=extraenv, action=action)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_venv.py", line 383, in _pcall
    return action.popen(args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_cmdline.py", line 100, in popen
    stdout=stdout, stderr=STDOUT)
  File "/Users/terry/.virtualenvs/lmwamp/lib/python2.7/site-packages/tox/_cmdline.py", line 188, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

It seems to be failing on a `pip install` permission denied in my v-env, which is odd. I tried pip installing those things myself and got another issue:

```
$ pip install mock unittest2 coverage msgpack-python Twisted==12.1
[lots of output deleted]
    changing mode of /Users/terry/.virtualenvs/lmwamp/bin/tkconch to 755
    changing mode of /Users/terry/.virtualenvs/lmwamp/bin/trial to 755
    changing mode of /Users/terry/.virtualenvs/lmwamp/bin/twistd to 755
Compiling /Users/terry/.virtualenvs/lmwamp/build/linecache2/linecache2/tests/inspect_fodder2.py ...
  File "/Users/terry/.virtualenvs/lmwamp/build/linecache2/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax

Successfully installed unittest2 coverage Twisted traceback2 argparse linecache2
Cleaning up...
```

At that point I gave up :-)

**Pull request merged**
