### PR TITLE
sequential id generation

### PR DESCRIPTION
**Pull request by meejah**
Adds a sequential ID generator in BaseSession (that wraps at 2**53) to provide IDs for all the Request (session-scoped IDs) replacing use of util.id() for these IDs. Issue #419

### CODE REVIEW

**Comment by oberstet** [comment]
Looks good. Just one thing: could you replace the  generator by something simple? It doesn't add value, and since this is a hot function, I am wary of the performance impacts.

Something like in `BaseSession`:

```python
def __init__(self, ..):
    self._last_request_id = -1
```
and

```python
def _next_request_id(self):
     self._last_request_id += 1
     if self._last_request_id > 2**53: # replace 2**53 with constant? not sure how smart CPy/PyPy are
         self._last_request_id = 0
     return self._last_request_id
```

**Comment by meejah** [comment]
Okay, changed it like that; make sense. Also, I was starting the IDs at 1, not 0 like the spec says.

The generator *should* be the same, but yeah it's not as obvious and I don't actually know if there's overhead. generator might use slightly more memory too...

**Comment by meejah** [comment]
(Note that I just force-pushed the new, changed comits over this same branch...)

**Comment by oberstet** [comment]
@meejah perfect. thanks! yeah, generators ... minimize "unknowns" in this case is good I guess

**Comment by meejah** [comment]
Yeah, good call on eliminating needless complexity ;) (it's now way easier to read the code).

**Pull request merged**
